version: '3'
services:
  web:
    build: './web'
    restart: always
    ports:
      - "5001:5000"
    depends_on: 
      - mysqldb
    
  login:
    build: './login'
    restart: always
    ports:
      - "5002:5000"
    depends_on: 
      - mysqldb
        
  friend:
    build: './friends'
    restart: always
    ports:
      - "5003:5000"
    depends_on: 
      - mysqldb

  socket:
    build: './sockets'
    restart: always
    ports:
      - "5004:5000"
     
  mysqldb:
    image: mysql/mysql-server:latest
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - /var/lib/docker/volumes/mysql_data/_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./web/build:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - login
      - friend
      - socket